### ISSUE TITLE
List sources of sample data

### ISSUE THREAD

**Issue by joshmoore** [ome/ngff#140]
@folterj was looking for sample datasets and came across three (unsuitable) locations:

 * https://github.com/ome/ome-zarr-py/tree/master/tests/data (dataless to keep the small)
 * https://www.openmicroscopy.org/2020/11/04/zarr-data.html (older version)
 * A hackmd where we are preparing just this list :smile:

The spec page itself should be the definitive starting point (for now) to find sample data.

**Comment by folterj** [comment]
Hi @joshmoore 
I didn't realise it's possible to open a Zarr by URL and after updating packages (in particular the obscure 'aiohttp') this is working fine. It may be nice to have some smaller samples as downloadable archives, but I understand the whole point of distributed/Zarr is de online accessibility.

**Comment by joshmoore** [comment]
@folterj: so you would want Zips for a single download, rather than needing to use `aws` or `mc` to download from S3? Btw, ome-zarr-py provides a download method, but dedicated tools are more scalable.

**Comment by folterj** [comment]
@joshmoore yes exactly.
By the way thank you also for making me aware of this page including up-to-date v0.4 samples - this is really nicely done!
https://idr.github.io/ome-ngff-samples/

**Comment by joshmoore** [comment]
> @joshmoore yes exactly.

Understood. We'll look into putting some more (smaller) samples up on Zenodo, but for now you can see find a handful under:

https://zenodo.org/search?page=1&size=20&q=ngff&access_right=open&type=dataset

**Comment by jburel** [comment]
* https://idr.github.io/ome-ngff-samples/
* https://uk1s3.embassy.ebi.ac.uk/bia-zarr-test/bia_examples.html
* https://s3.embl.de/i2k-2020/platy-raw.ome.zarr (https://s3.embl.de/i2k-2020)
* https://webknossos.org/datasets/scalable_minds/l4dense_motta_et_al_demo#2924,4474,1770,0,3.4
* Links to consider in https://hackmd.io/@ome/HJq5cSNV5

**Comment by joshmoore** [comment]
Discussing with @erindiel, @jburel, and @pwalczysko today regarding the upcoming publication, there's a general sense that along with `ngff.openmicroscopy.org` we can maintain a single page "data resources" page that then points to:
 - known collections of actual datasets (like https://idr.github.io/ome-ngff-samples)
 - lists of repositories tagged with a given topic (e.g. "ome-zarr-catalog")

A similar strategy is likely to be followed for a top-level landing page for "tool resources" which then in turn links the tools (as https://ome.github.io/ome-ngff-tools does) as well as discovered repositories.

**Comment by joshmoore** [comment]
Thinks this has been reasonably covered
