### ISSUE TITLE
units instead of unit

### ISSUE THREAD

**Issue by will-moore** [ome/ngff#156]
As reported https://github.com/scalableminds/webknossos/issues/6577#issuecomment-1298531394
some of our sample data uses `"units"` for `v0.4 axes`
when the spec says `"unit"`: https://ngff.openmicroscopy.org/latest/#axes-md

Checking the ngff repo I see that the schema uses "units": https://github.com/ome/ngff/blob/0a087b8319b234a0682bc4853e390314f76f7540/0.4/schemas/image.schema#L127
whereas the example files use "unit"
https://github.com/ome/ngff/blob/main/0.4/examples/multiscales_strict/multiscales_example.json
and some of the test files use both! https://github.com/ome/ngff/blob/0a087b8319b234a0682bc4853e390314f76f7540/0.4/tests/strict_image_suite.json

I guess the issue here is that having "unit" when the schema states "units" is not actually invalid, as the schema allows unknown keys to be added.

**Comment by sbesson** [comment]
Looking at the history of 0.4 and especially https://github.com/ome/ngff/pull/57, I suspect the confusion comes from the fact that the initial implementation had a field called `units` and this got transformed into `unit` (specifically in https://github.com/ome/ngff/pull/57/commits/70ebede458dc74f34f5714ba304092ffb547cc40).

Although an `units` field is not invalid per se, the specification uses `unit` and I think our examples, our validation and generation tools should exclusively use this terminology. Related to the example above, I see a few places that should be updated:

1. the JSON schemas & the associated JSON test files
2. the `omero-cli-zarr` generation tool - see https://github.com/ome/omero-cli-zarr/blob/9cce537d049531e565a6a9eec77498f82c97a0c0/src/omero_zarr/util.py#L47-L51
