### ISSUE TITLE
Find out what labeled object represents if names to labels have not been given

### ISSUE THREAD

**Issue by aliaksei-chareshneu** [ome/ngff#164]
Dear all,

Could you tell me please, how can one find out what each labeled object actually represents (nucleus, mitochondria etc.) if names to labels (like here: https://ome.github.io/ome-ngff-validator/?source=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0052A/5514375.zarr/labels) have not been given (which is the case of https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0062A/6001240.zarr)?

Thank you for any input,
Aliaksei

**Comment by will-moore** [comment]
Answered at https://forum.image.sc/t/interpreting-ome-zarr-ngff-data/74459/2
