### ISSUE TITLE
Multiscales questions

### ISSUE THREAD

**Issue by tischi** [ome/ngff#17]
@joshmoore @will-moore 
Multiscales is an array: `Multiscale[] multiscales = n5.getAttribute( "", "multiscales", Multiscale[].class );`
I don't understand in which scenarios this array could have more than one item?

**Comment by tischi** [comment]
@joshmoore 

Thanks! I guess for opening this in BDV we for now just pick `multiscales[ 0 ]`, ok? 
Implementing a good logic for opening alternative pyramids feels like a more complex project to me.

**Comment by joshmoore** [comment]
Agreed.

**Comment by constantinpape** [comment]
This is a very old discussion, so I am closing this.

**Comment by joshmoore** [comment]
Thanks for the clean up, @constantinpape. I think the use of the multiple multiscales is still not well formulated (see question during the 6th NGFF call) but happy for that to be in a follow-up issue/PR.

**Comment by constantinpape** [comment]
@joshmoore my strategy right now is just to collect all the "low hanging fruit" follow ups in https://github.com/ome/ngff/issues/86 and then spin off issue(s) from that one as soon as 0.4 is released - could you just leave a comment there regarding the multiple multiscales?

**Comment by joshmoore** [comment]
Perfect strategy. Thanks.
