### ISSUE TITLE
Change `version` field(s) from SHOULD to MUST

### ISSUE THREAD

**Issue by keller-mark** [ome/ngff#185]
Being able to rely on the `version` (either at top-level https://github.com/ome/ngff/issues/83) or within the individual metadata fields would make implementation of parsers / readers easier - avoiding the need to guess which schema version a particular OME-NGFF or metadata field conforms to.

This seems particularly important for allowing potential semantic changes between spec versions that might not be able to be inferred from data types (e.g., based on whether `axes` elements are strings vs. objects)

**Comment by will-moore** [comment]
https://github.com/ome/ngff/pull/186
