### ISSUE TITLE
Z-downsampling metadata

### ISSUE THREAD

**Issue by will-moore** [ome/ngff#25]
It's possible that we may generate multiple `"datasets"` for a given OME-Zarr Image, e.g. with and without down-sampling in Z. It could be useful to have a way to identify these.

See https://github.com/hms-dbmi/vizarr/pull/71#issuecomment-760261353
"will there be any way to distinguish between the downsampled-in-z version of a dataset and the non-downsampled version? The shape of the zarr array, I presume? But will there be any metadata about it? Just curious........."

@joshmoore "One thing we could do at the moment (pre-lightsheet changes) would be to have a naming convention for the multiscales themselves. Another option would be to use the metadata for the method of the downsampling, but we’d need something well-defined to say “in-z".

**Comment by ilan-gold** [comment]
Just out of curiosity @will-moore @joshmoore, what are the "lightsheet changes?"

**Comment by joshmoore** [comment]
Hi @ilan-gold. The next body of work is focused around having better support for large 3D volumes. We'll likely use the opportunity to making the first breaking changes to the metadata (0.1 --> 0.2) so if there's something that's needed (e.g. the way to detect the z-downsampled multiscale zgroup as you were asking in https://github.com/hms-dbmi/vizarr/pull/71#issuecomment-760261353) then this would be a good time to do it.

**Comment by ilan-gold** [comment]
Gotcha @joshmoore, I know @will-moore and I talked on image.sc about scaling as well, derived from the reported physical size, so that would be great too in the next change.  We are very interested in this 3D stuff as well so I'll keep my ear to the ground.

**Comment by constantinpape** [comment]
The downsamplling is now specified using `coordinateTransformations:scale` in v0.4; so the downsampling across all spatial dimensions is transparent.
