### ISSUE TITLE
Napari plugin for ome-zarr

### ISSUE THREAD

**Issue by constantinpape** [ome/ngff#49]
We are currently working on generating reference data for ome.zarr v0.3 (see #46 ) and providing a fiji plugin for opening it through MoBIE, see https://github.com/mobie/mobie.github.io/issues/52.

I think that it would be good to have a plugin in napari as well to have a second reference implementation for opening it.
Is there some "official" napari plugin for ome.zarr already that this could be integrated into?
If not, I could write something for 0.3, but I would need a pointer on the latest instructions for writing napari plugins.

cc @jni @sofroniewn

**Comment by will-moore** [comment]
Currently it is https://github.com/ome/ome-zarr-py but we are in the process of separating the napari plugin code from ome-zarr and moving it to https://github.com/ome/napari-ome-zarr

**Comment by constantinpape** [comment]
Thanks @will-moore. I will have a look at https://github.com/ome/napari-ome-zarr.
