### ISSUE TITLE
Spec naming style

### ISSUE THREAD

**Issue by will-moore** [ome/ngff#54]
When looking to add new keys to the spec I wonder how to name e.g. [position_x](https://github.com/ome/ngff/issues/31#issuecomment-910260493) I wonder what the naming style should be e.g.

- position_x
- positionX
- position-x
- positionx

Looking at the current spec, we have all of these styles there already, reflecting the origin of various terms (mea culpa):
 - `image-label`
 - `defaultT` - Rendering definition (omero). to be replaced by rendering spec?
 - `maximumfieldcount` - HCS, to be replace by Collections spec
 - `field_count` - Also HCS.

So, which of these do we prefer? Python style, Java style or something else?

**Comment by constantinpape** [comment]
We should absolutely have a consistent naming style. I would personally vote for snake case (python style) but I don't have a strong opinion and camel case (java style) would also be fine with me.

**Comment by glyg** [comment]
I agree with @constantinpape (1. snake case, 2. camelCase) with a rather strong rejection of the "postion-x" just because I know I'll have to parse out the dash sign at some point and I'm lazy, and a _very_ strong rejection of "positionx" because it will be confusing with e.g. the curvilinear coordinate "s"

**Comment by joshmoore** [comment]
Similar to the "dashes don't work great in programming languages", I'd add that casing isn't always that clear with URLs. Since I expect these identifiers will eventually get used in such contexts, I'd favor `position_x` over `positionX`.

**Comment by jburel** [comment]
If we wish to follow the style in place in schema.org, ``positionX`` should be used

**Comment by joshmoore** [comment]
@glyg had the strongest objection in https://github.com/ome/ngff/issues/54#issuecomment-911330048. I'm personally fine with underscores (i.e. more PEP8)

**Comment by constantinpape** [comment]
I read https://github.com/ome/ngff/issues/54#issuecomment-911330048 as being fine with both camel or snake case, just objecting (rightfully in my opinion) to `position-x` or `positionx`.

**Comment by joshmoore** [comment]
Ah, I see. I misread.

**Comment by will-moore** [comment]
I don't know if we're actually going to use schema.org, but it seems that many schemas and data-models tend to use `camelCase` so in the interests of consistency I think that makes the most sense.
I think @joshmoore is OK with `camelCase` too?
So hopefully that's looking like a new consensus...
