### ISSUE TITLE
<code data-opaque bs-autolink-syntax='

### ISSUE THREAD

**Issue by will-moore** [ome/ngff#62]
In https://ngff.openmicroscopy.org/latest/#image-layout I see a bunch of:

```
<code data-opaque bs-autolink-syntax='
```

which seem to be caused by ` in the docstring e.g. at https://github.com/ome/ngff/blob/5b9d2b23d021331b847074ff678cd368de32d95a/latest/index.bs#L142

**Comment by glyg** [comment]
I tried substituting the triple backticks by `<pre>` tags and it does remove the `<code opaque ` clutter but also removes the backticks in the comments:

http://api.csswg.org/bikeshed/?url=https://github.com/glyg/ngff/raw/back-tick/latest/index.bs

Maybe it's better to use `<pre> ... </pre>` as it's more robust anyway?

**Comment by will-moore** [comment]
I see the ```<code>``` elements are still there in the HTML, so the backticks are still having an effect, it's just that the styling of those elements is no different from the surrounding text.
But 👍  for the "bug fix".
