### ISSUE TITLE
document client feature support

### ISSUE THREAD

**Issue by will-moore** [ome/ngff#71]
As the spec evolves, it's increasing likely that there will be parts of it that are not supported by all the clients, either because of technical limitations or the work just hasn't been done/released.

It would be really nice for new and existing users to be able to see what is supported by which clients, or what's NOT supported (without having to search the issues of each repo). This would also be a nice way to show what clients are available to view OME-NGFF data.

I'm thinking of something like a support table, similar to e.g. https://caniuse.com/flexbox (although in that case it's a table for a single feature, with different versions of each tool). I'd suggest we limit it to documenting only the latest release of each tool.

| viewer | Z-downsampling | omero info | multiscales factor not=2 | URL (not s3) | v0.3 axes | 3D view | labels | HCS plate |
|-------|------------------|------------|-------------------------|--------------|-----------|---------|-------|-----|
| napari | y | y | y | y | y | y (1) |  y | y |
| vizarr | [n](https://github.com/hms-dbmi/vizarr/pull/71) | y | [n](https://github.com/hms-dbmi/vizarr/issues/101) | y | y | n | n| y |
|MoBIE | y | n | y | [n](https://github.com/mobie/mobie-viewer-fiji/issues/351) | n | y | y | n|

1) napari 3D view only supported for lowest level of multiscales pyramid

If this looks like a popular idea, where would this doc/table live? Include it in the spec page, or a doc page on this repo?

**Comment by joshmoore** [comment]
cc: @manzt @constantinpape

**Comment by constantinpape** [comment]
This would be great to have!

**Comment by manzt** [comment]
Agreed, great idea!
