### ISSUE TITLE
affines and dimensions

### ISSUE THREAD

**Issue by satra** [ome/ngff#74]
if i may make one comment that we allow `affines` back as transformation. but optional and if included then translation and scale should not be used. for some of our use cases it would be really nice to be able to include the affine in the dataset itself rather than separately. we can wait till the next iteration of the spec, but if there are no objections that affines will also be `axisIndices` or dimension compliant, i don't see a reason why including it would be difficult. 

let me first start with dimensions. at present it is time, channel, shape, shape, shape. while time can cover many aspects, we may want to include something like slice, channel, shape, shape, shape for 3d imaging, where we take a 3d tissue and slice it into thinner slices and then put them together as a single dataset. 

this has a few additional requirements and this is where the affine part comes in.  although a computed transform, it may be helpful to align these slices in 3D space. also we may have missing slices or uneven spacing. thus having affines be associated with each slice could be helpful.

in out practical use case, we have stains, not channels. so our dimensions would be:

`slice, stain_index, shape, shape, shape, chunk`

where chunks are partially overlapping acquisitions. chunks would be dropped if the images were prestitched.

in this use case, the affines  could be associated with different slices and potentially chunks.  for simplicity let's leave chunks aside. 

then our transformations would be a list of affines for each slice `[ aff1, aff2, ....]` where the `axisIndices` would be `[2,3,4]` and the `aff*` would be `[4x4]`  since `axisIndices` is of length 3.

thus there are a few requests here.

1. that we allow arbitrary dimensions
2. list of affines as transformations. since each slice could have been arbitrarily rotated and flipped (front to back) having a computed affine could really help place all the pieces together
3. additional metadata to situation the coordinate system better w.r.t some physical property of the sample by defining a global origin. 

this figure may help visualize the situation: https://scalablebrainatlas.incf.org/human/BIGB13

cc: @thewtex

**Comment by thewtex** [comment]
It seems that we are progressing towards addressing this use case.

**Comment by constantinpape** [comment]
I will close this in favor of the transformation proposal that's taking shape in #94. Would be great to get your input there @satra. Feel free to reopen this one if you think something here is especially relevant.
