### ISSUE TITLE
json-schema for v0.4 spec

### ISSUE THREAD

**Issue by will-moore** [ome/ngff#82]
As mentioned by @constantinpape, we should update JSON-schemas for v0.4 spec.

**Comment by sbesson** [comment]
At the moment we only have JSON schemas for the image level (`multiscales` specification). Is the expectation to also produce JSON schemas for other levels (plate, well, labels, image-label) or should we restrict this to `image` first?

**Comment by will-moore** [comment]
Yes, we should certainly extend the coverage. But probably once v0.4 is ready for `multiscales` then that could get merged ahead of covering other levels.
